name: E2E tests

on:
  push:
    branches: [main, next]
  pull_request:
  workflow_dispatch:

jobs:
  run-tests:
    name: E2E tests
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci
      - run: npm run build
      - run: npm run test:e2e:install

      - name: Run tests
        run: npm run test:e2e

      - uses: daun/playwright-report-summary@v2
        with:
          report-file: playwright-results.json
